title: yay.se                                 # Name of the site
author:
  name: Olof Brickarp                      # Default author name
  email: 'olle@yay.se'                   # Default author email
taxonomies: [category,tag]                  # Arbitrary list of taxonomy types
metadata:
    description: 'The thoughts and work of Olof Brickarp'             # Site description
summary:
  size: 300                                 # Maximum length of summary (characters)
routes:
  /something/else: '/blog/sample-3'         # Alias for /blog/sample-3
  /another/one/here: '/blog/sample-3'       # Another alias for /blog/sample-3
  /new/*: '/blog/*'                         # Wildcard any /new/my-page URL to /blog/my-page Route
